name: Rust + Python CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install maturin
      run: pip install maturin

    # ───────── Rust 语法/编译检查 ─────────
    - name: cargo check
      run: cargo check --workspace --all-targets

    # ───────── Build wheel ─────────
    - name: Build wheel with maturin
      run: |
        set -e
        # 把 wheel 统一放到 ./wheelhouse
        maturin build --release \
          --manifest-path pku3b_py/Cargo.toml \
          --interpreter python${{ matrix.python-version }} \
          --out wheelhouse
        ls -l wheelhouse

    # ───────── Install wheel ─────────
    - name: Install wheel
      run: pip install wheelhouse/*.whl

    # ───────── 烟雾测试 ─────────
    - name: Import test
      run: |
        python - <<'PY'
        import pku3b_py, pathlib, sys
        print("✅  import ok:", pku3b_py.__name__)
        print("wheel path  :", pathlib.Path(pku3b_py.__file__).parent)
        print("python      :", sys.version)
        PY